### ISSUE TITLE
unreproducible classification accuracy for 10 tasks

### ISSUE THREAD

**Issue by qichenglao** [WuChenshen/MeRGAN#4]
Hi, thanks for sharing the code. 
I am trying to reproduce your work. For both datasets (mnist and svhn), the classification accuracy for the 5 tasks are the same as in the paper. However, for the 10 tasks, I only got ~0.94 for the mnist and ~0.63. for svhn.
Is there anything missing in the code in order to reproduce your results in the paper?

**Comment by qichenglao** [comment]
Sorry, it is reproduced by increasing iteration to 8001 for mnist.

**Comment by liuziye1997** [comment]
Why the accuracy of my running results is close to zero for the previous categories？ That is, each prediction is predicted as the last category.
